import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NoteEase || Best Notes App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster
          toastOptions={{
            success: {
              iconTheme: {
                primary: "#2B85FF",
                secondary: "white",
              },
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
